# Generated by Django 5.2.5 on 2026-01-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('github', models.URLField(blank=True, max_length=500, null=True)),
                ('figma', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
