# Generated by Django 5.2.5 on 2026-01-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_forks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='github_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='github_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
