# Generated by Django 5.2.5 on 2026-01-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_category_project_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_figma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_app_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_backend_by_me',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_web_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
