# Generated by Django 5.2.5 on 2026-01-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_has_figma_project_has_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='app_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
