# Generated by Django 5.2.5 on 2026-01-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_app_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='api_docs_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='built_during',
            field=models.CharField(choices=[('college', 'College Project'), ('freelance', 'Freelance Work'), ('personal', 'Personal Experiment'), ('hackathon', 'Hackathon'), ('professional', 'Professional/Job')], default='personal', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='languages_distribution',
            field=models.JSONField(blank=True, default=dict, help_text='e.g., {"Python": 60, "JS": 40}'),
        ),
        migrations.AddField(
            model_name='project',
            name='lighthouse_accessibility',
            field=models.PositiveIntegerField(default=0, help_text='0-100'),
        ),
        migrations.AddField(
            model_name='project',
            name='lighthouse_performance',
            field=models.PositiveIntegerField(default=0, help_text='0-100'),
        ),
        migrations.AddField(
            model_name='project',
            name='lighthouse_seo',
            field=models.PositiveIntegerField(default=0, help_text='0-100'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='related_projects',
            field=models.ManyToManyField(blank=True, to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='test_coverage',
            field=models.PositiveIntegerField(default=0, help_text='Percentage (e.g., 95)'),
        ),
    ]
