# Generated by Django 5.2.5 on 2026-01-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_api_docs_link_project_built_during_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
