# Generated by Django 5.2.5 on 2026-01-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('spam', 'Spam'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='hiringrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
