# Generated by Django 5.2.5 on 2026-01-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatsession_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=dict)),
                ('social_links', models.JSONField(blank=True, default=list)),
                ('resume_url', models.URLField(blank=True, max_length=500, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
