# Generated by Django 5.2.5 on 2026-01-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='tech_stack',
            new_name='achievements',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='company_name',
            new_name='company',
        ),
        migrations.AddField(
            model_name='experience',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
