# Generated by Django 5.2.5 on 2026-01-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_rename_tech_stack_experience_achievements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('score', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', 'id'],
            },
        ),
    ]
